name: Birthday Cron Job (Testing)

on:
  schedule:
    - cron: "*/1 * * * *"   # every 1 minute

jobs:
  build:
    name: Birthday checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run birthday script
