name: Birthday Cron Job (Testing)

on:
  schedule:
    - cron: "*/1 * * * *"   # every 1 minute
  workflow_dispatch:

jobs:
  check-birthdays:
    runs-on: ubuntu-latest
    steps:
      - name: Run birthday script
        uses: actions/checkout@v3
        with:
          node-version: '16.x'

      - name: Run birthday script
        run:   |
         npm install
         node index.js
